site_name: Post-SSRI Syndrome
site_url: https://postssrisyndrome.github.io
theme:
  name: mkdocs
  locale: it
  nav_style: primary  # 'dark' or 'light'
plugins:
    - search:
        lang: it
        # indexing values: 'full' (default), 'sections', 'titles'
        indexing: 'full'
extra_css:
    - css/extra.css
nav:
  - News: news.md
  - "La sindrome":
    - la-sindrome/caratteristiche.md
    - "Quanto Ã¨ comune?": la-sindrome/prevalenza.md
    - "Quali farmaci sono coinvolti?": la-sindrome/farmaci.md
    - la-sindrome/criteri-diagnostici.md
    - la-sindrome/storie.md
  - Ricerca:
    - "Ricerca in corso": ricerca/ricerca-in-corso.md
    - ricerca/pubblicazioni.md
    - "Aiutare la ricerca": https://www.gofundme.com/f/27l8qmes5c
  - Media:
    - "Divulgazione medica": media/medici.md
    - media/articoli.md
    - media/video.md
  - Risorse:
    - risorse/organismi.md
    - Forum: https://www.pssdforum.org
    - risorse/links.md
  - Donazioni: https://www.gofundme.com/f/27l8qmes5c
